FROM desub:cu124
RUN pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple \
    diffusers==0.29.2 accelerate==0.25.0 transformers==4.41.1 \
    einops==0.8.0 peft==0.13.2 scipy==1.13.1 av==14.0.1 datasets==2.19.1 \
    "numpy==1.26.4" "pillow==10.4.0" "urllib3==2.2.2" "zipp==3.19.2"
